version: "3"
services:
  zookeeper: # this is the config manager
    container_name: zookeeper
    user: root
    hostname: zookeeper
    image: "bitnami/zookeeper:latest"
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  nifi:
    container_name: nifi
    user: root
    depends_on:
      - zookeeper
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_logs:/opt/nifi/nifi-current/logs
    image: apache/nifi:latest
    ports:
      - 9443:9443
    environment:
      - NIFI_WEB_HTTPS_PORT=9443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=TwFw2D6Z11Mz
      # - NIFI_HOME=/opt/nifi/nifi-current
      # - NIFI_LOG_DIR=/opt/nifi/nifi-current/logs
      # - NIFI_TOOLKIT_HOME=/opt/nifi/nifi-toolkit-current
      # - NIFI_PID_DIR=/opt/nifi/nifi-current/run
      # - NIFI_BASE_DIR=/opt/nifi

volumes:
  nifi_conf:
    external: true
  nifi_database_repository:
    external: true
  nifi_flowfile_repository:
    external: true
  nifi_content_repository:
    external: true
  nifi_provenance_repository:
    external: true
  nifi_state:
    external: true
  nifi_logs:
    external: true

networks:
  default:
    external:
      name: poc